export {default as Navbar} from'./Navbar/Navbar';
export {default as Hero} from './Hero/Hero';
export {default as HeroTwo} from './Hero/HeroTwo';
export {default as HeroThree} from './Hero/HeroThree';
export {default as About} from './About/About';
export {default as CardsAbout} from './Cards/CardsAbout/CardsAbout';
export {default as CardsService} from './Cards/CardsService/CardsService';
export {default as BannerOne} from './Banner/BannerOne/BannerOne';
export {default as BannerTwo} from './Banner/BannerTwo/BannerTwo';
export {default as BannerThree} from './Banner/BannerThree/BannerThree';
export {default as ContentOne} from "./Content/ContentOne/ContentOne";
export {default as ContentTwo} from './Content/ContentTwo/ContentTwo';
export {default as ContentThree} from './Content/ContentThree/ContentThree';
export {default as ContentFour} from './Content/ContentFour/ContentFour';
export {default as FooterOne} from './Footer/FooterOne/FooterOne';